/**
 * Generated by scripts/build-palette.js. Do not edit by hand.
 * Source of truth: resources/[vector]/vector-palette/src/tokens.json
 * Bound to VEC-21 §3 art-direction. Updates require a CEO-approved revision of that document.
 */

const palette = Object.freeze({
  world: Object.freeze({
    softBlack: Object.freeze({ r: 11, g: 12, b: 14, a: 1, hex: "#0B0C0E", name: "world.softBlack" }),
    asphalt: Object.freeze({ r: 31, g: 34, b: 38, a: 1, hex: "#1F2226", name: "world.asphalt" }),
    concrete: Object.freeze({ r: 74, g: 78, b: 85, a: 1, hex: "#4A4E55", name: "world.concrete" }),
    bone: Object.freeze({ r: 242, g: 237, b: 227, a: 1, hex: "#F2EDE3", name: "world.bone" }),
  }),
  hud: Object.freeze({
    text: Object.freeze({ r: 242, g: 237, b: 227, a: 1, hex: "#F2EDE3", name: "hud.text" }),
    plate: Object.freeze({ r: 11, g: 12, b: 14, a: 0.6, hex: "#0B0C0E", name: "hud.plate" }),
    money: Object.freeze({ r: 93, g: 176, b: 122, a: 1, hex: "#5DB07A", name: "hud.money" }),
    alert: Object.freeze({ r: 224, g: 23, b: 59, a: 1, hex: "#E0173B", name: "hud.alert" }),
    warning: Object.freeze({ r: 255, g: 179, b: 71, a: 0.7, hex: "#FFB347", name: "hud.warning" }),
  }),
  scene: Object.freeze({
    sodium: Object.freeze({ r: 255, g: 138, b: 43, a: 1, hex: "#FF8A2B", name: "scene.sodium" }),
    policeBlue: Object.freeze({ r: 42, g: 107, b: 255, a: 1, hex: "#2A6BFF", name: "scene.policeBlue" }),
    jewelryNeon: Object.freeze({ r: 255, g: 61, b: 139, a: 1, hex: "#FF3D8B", name: "scene.jewelryNeon" }),
  }),
});

function withAlpha(token, alpha) {
  if (!token || typeof token !== "object") {
    throw new Error("withAlpha expects a palette entry");
  }
  if (typeof alpha !== "number" || alpha < 0 || alpha > 1) {
    throw new Error("withAlpha expects alpha in [0,1]");
  }
  return Object.freeze({ ...token, a: alpha });
}

module.exports = { palette, withAlpha };
