-- Generated by scripts/build-palette.js. Do not edit by hand.
-- Source of truth: resources/[vector]/vector-palette/src/tokens.json
-- Bound to VEC-21 §3 art-direction. Updates require a CEO-approved revision of that document.

local function entry(group, token, r, g, b, a, hex)
    return {
        r = r,
        g = g,
        b = b,
        a = a,
        hex = hex,
        name = group .. "." .. token,
    }
end

local raw = {}
raw.world = {}
raw.world.softBlack = entry("world", "softBlack", 11, 12, 14, 1, "#0B0C0E")
raw.world.asphalt = entry("world", "asphalt", 31, 34, 38, 1, "#1F2226")
raw.world.concrete = entry("world", "concrete", 74, 78, 85, 1, "#4A4E55")
raw.world.bone = entry("world", "bone", 242, 237, 227, 1, "#F2EDE3")
raw.hud = {}
raw.hud.text = entry("hud", "text", 242, 237, 227, 1, "#F2EDE3")
raw.hud.plate = entry("hud", "plate", 11, 12, 14, 0.6, "#0B0C0E")
raw.hud.money = entry("hud", "money", 93, 176, 122, 1, "#5DB07A")
raw.hud.alert = entry("hud", "alert", 224, 23, 59, 1, "#E0173B")
raw.hud.warning = entry("hud", "warning", 255, 179, 71, 0.7, "#FFB347")
raw.scene = {}
raw.scene.sodium = entry("scene", "sodium", 255, 138, 43, 1, "#FF8A2B")
raw.scene.policeBlue = entry("scene", "policeBlue", 42, 107, 255, 1, "#2A6BFF")
raw.scene.jewelryNeon = entry("scene", "jewelryNeon", 255, 61, 139, 1, "#FF3D8B")

local function deepFreeze(t)
    for _, v in pairs(t) do
        if type(v) == "table" then deepFreeze(v) end
    end
    return setmetatable({}, {
        __index = t,
        __newindex = function()
            error("vector-palette is read-only — edit src/tokens.json and regenerate", 2)
        end,
        __metatable = false,
    })
end

local palette = {}
palette.world = deepFreeze(raw.world)
palette.hud = deepFreeze(raw.hud)
palette.scene = deepFreeze(raw.scene)

function palette.withAlpha(token, alpha)
    if type(token) ~= "table" then
        error("withAlpha expects a palette entry table", 2)
    end
    if type(alpha) ~= "number" or alpha < 0 or alpha > 1 then
        error("withAlpha expects alpha in [0,1]", 2)
    end
    return {
        r = token.r,
        g = token.g,
        b = token.b,
        a = alpha,
        hex = token.hex,
        name = token.name,
    }
end

return deepFreeze(palette)
