#!/usr/bin/env node
// Generator for the vector-palette module.
// Source of truth: resources/[vector]/vector-palette/src/tokens.json (bound to VEC-21 §3).
// Emits palette.lua, palette.js, palette.css. Do not hand-edit those files.

"use strict";

const fs = require("fs");
const path = require("path");

const REPO_ROOT = path.resolve(__dirname, "..");
const RESOURCE_DIR = path.join(REPO_ROOT, "resources", "[vector]", "vector-palette");
const SRC_TOKENS = path.join(RESOURCE_DIR, "src", "tokens.json");

const OUT_LUA = path.join(RESOURCE_DIR, "palette.lua");
const OUT_JS = path.join(RESOURCE_DIR, "palette.js");
const OUT_CSS = path.join(RESOURCE_DIR, "palette.css");

const GENERATED_BANNER = [
  "Generated by scripts/build-palette.js. Do not edit by hand.",
  "Source of truth: resources/[vector]/vector-palette/src/tokens.json",
  "Bound to VEC-21 §3 art-direction. Updates require a CEO-approved revision of that document.",
];

function fail(msg) {
  process.stderr.write(`build-palette: ${msg}\n`);
  process.exit(1);
}

function parseHex(hex) {
  const m = /^#([0-9A-Fa-f]{6})$/.exec(hex);
  if (!m) fail(`invalid hex literal: ${hex}`);
  const n = parseInt(m[1], 16);
  return {
    r: (n >> 16) & 0xff,
    g: (n >> 8) & 0xff,
    b: n & 0xff,
    hex: `#${m[1].toUpperCase()}`,
  };
}

function loadTokens() {
  const raw = fs.readFileSync(SRC_TOKENS, "utf8");
  let json;
  try {
    json = JSON.parse(raw);
  } catch (err) {
    fail(`tokens.json is not valid JSON: ${err.message}`);
  }
  if (!json.groups || typeof json.groups !== "object") {
    fail("tokens.json missing groups object");
  }
  const flat = [];
  for (const [groupName, groupBody] of Object.entries(json.groups)) {
    for (const [tokenName, def] of Object.entries(groupBody)) {
      const rgb = parseHex(def.hex);
      const alpha = typeof def.alpha === "number" ? def.alpha : 1.0;
      if (alpha < 0 || alpha > 1) fail(`alpha out of range for ${groupName}.${tokenName}`);
      flat.push({
        group: groupName,
        token: tokenName,
        full: `${groupName}.${tokenName}`,
        cssVar: `--vec-${groupName}-${kebab(tokenName)}`,
        ...rgb,
        a: alpha,
      });
    }
  }
  return { source: json, flat };
}

function kebab(s) {
  return s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
}

function rgbaCss(t) {
  return `rgba(${t.r}, ${t.g}, ${t.b}, ${formatAlpha(t.a)})`;
}

function formatAlpha(a) {
  // 0.6 → "0.6", 1.0 → "1", 0.123 → "0.123"
  return Number.isInteger(a) ? String(a) : String(parseFloat(a.toFixed(4)));
}

function emitLuaBanner() {
  return GENERATED_BANNER.map((l) => `-- ${l}`).join("\n");
}

function emitJsBanner() {
  return [
    "/**",
    ...GENERATED_BANNER.map((l) => ` * ${l}`),
    " */",
  ].join("\n");
}

function emitCssBanner() {
  return [
    "/*",
    ...GENERATED_BANNER.map((l) => ` * ${l}`),
    " */",
  ].join("\n");
}

function buildLua(tokens) {
  const groups = {};
  for (const t of tokens.flat) {
    (groups[t.group] = groups[t.group] || []).push(t);
  }
  const lines = [];
  lines.push(emitLuaBanner());
  lines.push("");
  lines.push("local function entry(group, token, r, g, b, a, hex)");
  lines.push("    return {");
  lines.push("        r = r,");
  lines.push("        g = g,");
  lines.push("        b = b,");
  lines.push("        a = a,");
  lines.push("        hex = hex,");
  lines.push('        name = group .. "." .. token,');
  lines.push("    }");
  lines.push("end");
  lines.push("");
  lines.push("local raw = {}");
  for (const groupName of Object.keys(groups)) {
    lines.push(`raw.${groupName} = {}`);
    for (const t of groups[groupName]) {
      lines.push(
        `raw.${groupName}.${t.token} = entry("${groupName}", "${t.token}", ${t.r}, ${t.g}, ${t.b}, ${formatAlpha(t.a)}, "${t.hex}")`,
      );
    }
  }
  lines.push("");
  lines.push("local function deepFreeze(t)");
  lines.push("    for _, v in pairs(t) do");
  lines.push('        if type(v) == "table" then deepFreeze(v) end');
  lines.push("    end");
  lines.push("    return setmetatable({}, {");
  lines.push("        __index = t,");
  lines.push("        __newindex = function()");
  lines.push('            error("vector-palette is read-only — edit src/tokens.json and regenerate", 2)');
  lines.push("        end,");
  lines.push("        __metatable = false,");
  lines.push("    })");
  lines.push("end");
  lines.push("");
  lines.push("local palette = {}");
  for (const groupName of Object.keys(groups)) {
    lines.push(`palette.${groupName} = deepFreeze(raw.${groupName})`);
  }
  lines.push("");
  lines.push("function palette.withAlpha(token, alpha)");
  lines.push('    if type(token) ~= "table" then');
  lines.push('        error("withAlpha expects a palette entry table", 2)');
  lines.push("    end");
  lines.push('    if type(alpha) ~= "number" or alpha < 0 or alpha > 1 then');
  lines.push('        error("withAlpha expects alpha in [0,1]", 2)');
  lines.push("    end");
  lines.push("    return {");
  lines.push("        r = token.r,");
  lines.push("        g = token.g,");
  lines.push("        b = token.b,");
  lines.push("        a = alpha,");
  lines.push("        hex = token.hex,");
  lines.push("        name = token.name,");
  lines.push("    }");
  lines.push("end");
  lines.push("");
  lines.push("return deepFreeze(palette)");
  return lines.join("\n") + "\n";
}

function buildJs(tokens) {
  const lines = [];
  lines.push(emitJsBanner());
  lines.push("");
  lines.push("const palette = Object.freeze({");
  const groups = {};
  for (const t of tokens.flat) (groups[t.group] = groups[t.group] || []).push(t);
  for (const [groupName, members] of Object.entries(groups)) {
    lines.push(`  ${groupName}: Object.freeze({`);
    for (const t of members) {
      lines.push(
        `    ${t.token}: Object.freeze({ r: ${t.r}, g: ${t.g}, b: ${t.b}, a: ${formatAlpha(t.a)}, hex: "${t.hex}", name: "${t.full}" }),`,
      );
    }
    lines.push("  }),");
  }
  lines.push("});");
  lines.push("");
  lines.push("function withAlpha(token, alpha) {");
  lines.push('  if (!token || typeof token !== "object") {');
  lines.push('    throw new Error("withAlpha expects a palette entry");');
  lines.push("  }");
  lines.push('  if (typeof alpha !== "number" || alpha < 0 || alpha > 1) {');
  lines.push('    throw new Error("withAlpha expects alpha in [0,1]");');
  lines.push("  }");
  lines.push("  return Object.freeze({ ...token, a: alpha });");
  lines.push("}");
  lines.push("");
  lines.push("module.exports = { palette, withAlpha };");
  return lines.join("\n") + "\n";
}

function buildCss(tokens) {
  const lines = [];
  lines.push(emitCssBanner());
  lines.push("");
  lines.push(":root {");
  for (const t of tokens.flat) {
    lines.push(`  ${t.cssVar}: ${t.hex};`);
    lines.push(`  ${t.cssVar}-rgba: ${rgbaCss(t)};`);
    lines.push(`  ${t.cssVar}-alpha: ${formatAlpha(t.a)};`);
  }
  lines.push("}");
  return lines.join("\n") + "\n";
}

function writeArtifact(file, content, check) {
  if (check) {
    const existing = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : "";
    if (existing !== content) {
      process.stderr.write(`build-palette: drift detected in ${path.relative(REPO_ROOT, file)}\n`);
      process.stderr.write("  run `node scripts/build-palette.js` and commit the result.\n");
      return false;
    }
    return true;
  }
  fs.writeFileSync(file, content);
  process.stdout.write(`wrote ${path.relative(REPO_ROOT, file)}\n`);
  return true;
}

function main() {
  const args = process.argv.slice(2);
  const check = args.includes("--check");
  const tokens = loadTokens();
  const lua = buildLua(tokens);
  const js = buildJs(tokens);
  const css = buildCss(tokens);
  const ok =
    writeArtifact(OUT_LUA, lua, check) &
    writeArtifact(OUT_JS, js, check) &
    writeArtifact(OUT_CSS, css, check);
  if (!ok) process.exit(1);
}

main();
